(define (require p)
  (if (not p) (amb)))

(define (distinct? items)
  (cond ((null? items) true)
        ((null? (cdr items)) true)
        ((member (car items) (cdr items)) false)
        (else (distinct? (cdr items)))))

(define (daughters)
  (define daughter car)
  (define (yacht p) (car (cdr p)))
  (let ((moore (list 'mary 'lorna))
        (barnacle (list 'melissa 'gabrielle))
        (hall (list (amb 'lorna 'gabrielle) 'rosalind))
        (downing (list (amb 'rosalind 'lorna 'gabrielle) 'melissa)))
    (require (not (eq? (daughter hall) (daughter downing))))
    (let ((parker (list (amb 'rosalind 'lorna) 'mary)))
      (require (not (eq? (daughter hall) (daughter parker))))
      (require (not (eq? (daughter downing) (daughter parker))))
      (if (eq? (daughter hall) 'gabrielle)
          (require (eq? (yacht hall) (daughter parker)))
          (require (eq? (yacht downing) (daughter parker))))
      (list (list 'moore moore)
              (list 'barnacle barnacle)
              (list 'hall hall)
              (list 'downing downing)
              (list 'parker parker)))))

(define (daughters-variant)
  (define daughter car)
  (define (yacht p) (car (cdr p)))
  (let ((barnacle (list 'melissa 'gabrielle))
        (moore (list (amb 'mary 'rosalind 'gabrielle) 'lorna))
        (hall (list (amb 'mary 'lorna 'gabrielle) 'rosalind)))
    (require (not (eq? (daughter moore) (daughter hall))))
    (let ((downing (list (amb 'mary 'rosalind 'lorna 'gabrielle) 'melissa)))
      (require (not (eq? (daughter moore) (daughter downing))))
      (require (not (eq? (daughter hall) (daughter downing))))
      (let ((parker (list (amb 'rosalind 'lorna) 'mary)))
        (require (not (eq? (daughter moore) (daughter parker))))
        (require (not (eq? (daughter hall) (daughter parker))))
        (require (not (eq? (daughter downing) (daughter parker))))
        (cond ((eq? (daughter moore) 'gabrielle) (require (eq? (yacht moore) (daughter parker))))
              ((eq? (daughter hall) 'gabrielle) (require (eq? (yacht hall) (daughter parker))))
              (else (require (eq? (yacht downing) (daughter parker)))))
        (list (list 'moore moore)
              (list 'barnacle barnacle)
              (list 'hall hall)
              (list 'downing downing)
              (list 'parker parker))))))

(define (daughters-old)
  (let ((mary 1)
        (gabrielle 2)
        (lorna 3)
        (rosalind 4)
        (melissa 5)
        (moore 6)
        (barnacle 7)
        (hall 8)
        (downing 9)
        (parker 10))
    (let ((mary-father moore)
          (moore-daughter mary)
          (moore-yacht lorna)
          (melissa-father barnacle)
          (barnacle-daughter melissa)
          (barnacle-yacht gabrielle)
          (hall-daughter 0)
          (hall-yacht rosalind)
          (downing-daughter 0)
          (downing-yacht melissa)
          (parker-daughter 0)
          (parker-yacht mary))
      (let ((rosalind-father (amb downing parker)))
        (cond ((= rosalind-father downing) (set! downing-daughter rosalind))
              (else (set! parker-daughter rosalind)))
        (let ((lorna-father (amb hall downing parker)))
          (require (not (= rosalind-father lorna-father)))
          (cond ((= lorna-father hall) (set! hall-daughter lorna))
                ((= lorna-father downing) (set! downing-daughter lorna))
                (else (set! parker-daughter lorna)))
          (let ((gabrielle-father (amb hall downing)))
            (require (not (= gabrielle-father lorna-father)))
            (require (not (= gabrielle-father rosalind-father)))
            (cond ((= gabrielle-father hall) (require (= hall-yacht parker-daughter)))
                  (else (require (= downing-yacht parker-daughter))))
            (require (distinct? (list mary-father melissa-father rosalind-father lorna-father gabrielle-father)))
            (list (list 'mary mary-father)
                  (list 'melissa melissa-father)
                  (list 'rosalind rosalind-father)
                  (list 'lorna lorna-father)
                  (list 'gabrielle gabrielle-father))))))))

(define (daughters-variant-old)
  (let ((mary 1)
        (gabrielle 2)
        (lorna 3)
        (rosalind 4)
        (melissa 5)
        (moore 6)
        (barnacle 7)
        (hall 8)
        (downing 9)
        (parker 10))
    (let ((moore-daughter 0)
          (moore-yacht lorna)
          (melissa-father barnacle)
          (barnacle-daughter melissa)
          (barnacle-yacht gabrielle)
          (hall-daughter 0)
          (hall-yacht rosalind)
          (downing-daughter 0)
          (downing-yacht melissa)
          (parker-daughter 0)
          (parker-yacht mary))
      (let ((mary-father (amb moore downing hall)))
        (cond ((= mary-father moore) (set! moore-daughter mary))
              ((= mary-father downing) (set! downing-daughter mary))
              (else (set! hall-daughter mary)))
        (let ((rosalind-father (amb moore downing parker)))
          (require (not (= rosalind-father mary-father)))
          (cond ((= rosalind-father moore) (set! moore-daughter rosalind))
                ((= rosalind-father downing) (set! downing-daughter rosalind))
                (else (set! parker-daughter rosalind)))
          (let ((lorna-father (amb hall downing parker)))
            (require (not (= mary-father lorna-father)))
            (require (not (= rosalind-father lorna-father)))
            (cond ((= lorna-father hall) (set! hall-daughter lorna))
                  ((= lorna-father downing) (set! downing-daughter lorna))
                  (else (set! parker-daughter lorna)))
            (let ((gabrielle-father (amb moore hall downing)))
              (require (not (= gabrielle-father mary-father)))
              (require (not (= gabrielle-father lorna-father)))
              (require (not (= gabrielle-father rosalind-father)))
              (cond ((= gabrielle-father moore) (require (= moore-yacht parker-daughter)))
                    ((= gabrielle-father hall) (require (= hall-yacht parker-daughter)))
                    (else (require (= downing-yacht parker-daughter))))
              (require (distinct? (list mary-father melissa-father rosalind-father lorna-father gabrielle-father)))
              (list (list 'mary mary-father)
                    (list 'melissa melissa-father)
                    (list 'rosalind rosalind-father)
                    (list 'lorna lorna-father)
                    (list 'gabrielle gabrielle-father)))))))))
