name: Build and Deploy Docs
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: jackfirth/racket:7.6-full
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y rsync

      - name: Build
        run: |
          Xvfb :1 -screen - 1024x768x16 &
          DISPLAY=:1.0 make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
